### ISSUE TITLE
how to damage my computer using your code?

### ISSUE THREAD

**Issue by randomwangran** [Horizon-Blue/playground#1]
>  I am not responsible for any damage that is caused by my code.

I am just curious about it.

**Comment by randomwangran** [comment]
don't be scare at my question... (ㆆ _ ㆆ)

I won't ask you a penny even if I crash my computer.  (̿▀̿‿ ̿▀̿ ̿)

I was actually inspired by you. (ᕗ ͠° ਊ ͠° )ᕗ

See, I have a similar rep like you: https://github.com/randomwangran/cpp/tree/master/learnCpp, except for CHAPTER00, which, in my opinion, looks like a PROgramer. ( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)

damage my computer using a bunch of c++ code is hard, in my opinion, unless you intentionally write virus kinda like of code, but it's whole new story.

**Comment by randomwangran** [comment]
Not receive any feedback from my dear friend. 

Well... Maybe you are busy with your projects.

Or maybe, you are not interested in playing with those things you used to like to play with.

whatever reason it is, just keep going, and perhaps, share those things you are interested in. I, or perhaps other people, am really appreciate it.

[I will continue my journey to this vast but fantastic world alone](https://github.com/randomwangran/my-0-1/tree/master).

If somehow, you get a tiny piece of time, please closed this issue.

**Comment by horizon-blue** [comment]
Ah, sorry. For some reason I've completely skipped this issue and never thought of checking my old repositories (´・ω・`)...

As for the damage, I don't have anything that intentionally break the systems or hide a secret `rm -rf /` in my code, though who knows whether I have something that accidentally cause a fork bomb? It is always better to be cautious. right?  lol

(Speaking of this, I believe I shall switch from MIT license to [GLWTPL](https://github.com/me-shaon/GLWTPL), which sounds a lot more appropriate in this case)

As you've probably noticed, it has been 2 years since my last major update on the C++ primer book. I did another update a year ago; other than that, this place is almost abandoned. I have reached the point where learning the surface form of programming language itself isn't that important anymore. C++ is still one of my most favorite programming languages; it is my starting point, it helped me build a solid foundation, and it led me to other possibilities. C++ isn't the language I use on daily basis -- in fact, I've never really work on any large scale project using C++. That's why I stop updating my progress on that book. I didn't forgot this project though, and I might catch up and finish the rest of the book some time in the future (for perfectionism).

I am happy to hear that you are inspired by my work... this is really a HUGE compliment to me  ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄. In any cases, good luck with your journey, keep going, and enjoy the fascinating world of programming :)

(btw I your Chapter 0 is super awesome lol)
